### PR TITLE
Cannot add new offers?

### PR DESCRIPTION
**Pull request by nicolocaruso85**
When i go through the link 
/admin/bat/config/global/offers/add
i get an ajax error?

## Expected Behavior
We need to get an interface to add offers as shown in the documentation

## Current Behavior
i get an error page as
image

### CODE REVIEW

**Comment by salvoscala** [comment]
Hi @ruvenshilpakar,
did you try to visit "/admin/bat/config/global/offers" and add offer clicking on the "Add Special Offer" button? We use a modal for that.

Thanks!

**Comment by ruvenshilpakar** [comment]
@salvoscala 
it works if you go through your approach, thank you for clarifying this. However, my issue is it a bug that need to be solved or its supposed to work as it is?

**Review by salvoscala — APPROVED** [review]
it works fine!

**Comment by salvoscala** [comment]
@ruvenshilpakar , I've merged this and it will be available in the next release (1.3.9).

Thank you!

**Pull request merged**
