### PR TITLE
Roomify

### PR DESCRIPTION
**Pull request by Misael78**
I need training in the Roomify i have to know what modules i need to active it i am beginer in drupal and i do not have experience in roomify i have bat and roomify modules in my localhost of drupal.
Please help me

### CODE REVIEW

**Comment by Misael78** [comment]
Thankyou for help me i want to know if some body can give me training about Roomify/RFA step by step (i need emergency training

**Comment by acrollet** [comment]
@Misael78 please open a separate issue with the label 'support request' for any support questions. If you'd like to purchase paid support/training, just let us know via email. thanks!

**Comment by acrollet** [comment]
@salvoscala should this be open as a PR? not sure what happened here.

**Comment by acrollet** [comment]
@Misael78 also, you may find installation documentation here: http://docs.roomify.us/accommodations_selfhost/index.html

**Comment by salvoscala** [comment]
No, @acrollet, don't need this PR right now. I guess it was just an error. 
The best solution would be to open a separate ticket @Misael78, thanks!

**Comment by Misael78** [comment]
Thank you
I am sorry I was confused, now I do understand 
atte. Misael Dubon

**Pull request closed without merging**
