### PR TITLE
Add an easy way to link the homepage to the properties lists nodes.

### PR DESCRIPTION
**Pull request by salvoscala**
Create a field in the homepage CT where a manager can link nodes of type Properties List

### CODE REVIEW

**Comment by salvoscala** [comment]
@acrollet can you please have a look at that? thanks :)

**Comment by acrollet** [comment]
@salvoscala let me know when the tests are passing and I'll give it a look, thanks! :)

**Comment by salvoscala** [comment]
@acrollet now this is ready for CR! :)

**Review by acrollet — APPROVED** [review]
CR passes :)

**Pull request merged**
