### PR TITLE
Update enquiries to use a custom form, with configurable text

### PR DESCRIPTION
**Pull request by salvoscala**
1. Create custom form to use for Enquiries
  a. Form Instructions text - blank by default
  b. Fields:
    i. Name
    ii. Email
    iii. Arrival date - taken from Search
    iv. Departure date - taken from Search
    v. Guests - taken from Search, if available
    vi. Further info
    vii. Listing Type
    viii. Price - taken from Search
  c. On submission:
    i. Populate conversation entity with data from form
    ii. Create user, and populate 'Guest' field in the conversation
    iii. Send emails (conversation confirmation to guest, notification of new enquiry to owner)
      1. Update the rules to ensure that the custom form submission triggers the emails being sent
    iv. Show user the submission reply
2. Update conversations to display enquiry data
  a. Add Fields:
    i. Name
    ii. Email
    iii. Guests
    iv. Further info
    v. Price
  b. Update Conversation Page according to attached comps
3. Add update hook to migrate existing entityform submission data to the associated conversation
4. Add update hook to migrate existing translations of the field names on the entityform and the submission confirmation text.
5. Add configuration form + permissions to enable text to be changed
  a. Configurable text:
    i. Submission reply - help text: "This text is shown on your site after a guest submits a booking enquiry."
    ii. Form instructions - help text: "This text is show to guests on the booking enquiry form."
  b. we need to confirm that these items are translatable via the string translation interface.
6. Add link to Dashboard in the 'Manage Configuration' tab: 'Enquiry Form settings' 

Enquiry info expanded in conversation:
enquiry_open

Enquiry info collapsed in conversation:
enquiry_closed

### CODE REVIEW

**Comment by cecrs** [comment]
@nicolocaruso85  Last thing - the price in a conversation needs to be re-styled:
format_price

**Review by cecrs — COMMENTED** [review]
Looks good!

**Review by cecrs — COMMENTED** [review]
Looking good

**Review by acrollet — APPROVED** [review]
lgtm

**Pull request merged**
