### PR TITLE
Test properties are not deleted after tests

### PR DESCRIPTION
**Pull request by acrollet**
Screenshot from 1.2.3 packaged version after login: admin accommodations 2016-12-28 09-10-15

### CODE REVIEW

**Comment by acrollet** [comment]
We will need to add the following to the release notes:

For this release only, the filesystem structure of the packaged version has been updated. If you are updating from a previous packaged release of RfA, you will need to run the following drush commands to update your database:

```bash
drush sqlq 'TRUNCATE TABLE registry_file'
drush -r ${SITE_DIR} sqlq 'UPDATE registry SET filename = REPLACE(filename, "sites/all/", "profiles/roomify/") WHERE filename LIKE "sites/all/%"'
drush sqlq 'UPDATE registry SET filename = REPLACE(filename, "sites/all/", "profiles/roomify/") WHERE filename LIKE "sites/all/%"'
drush sqlq 'UPDATE system SET filename = REPLACE(filename, "sites/all/", "profiles/roomify/") WHERE filename LIKE "sites/all/%"'
drush sqlq 'UPDATE menu_router SET include_file = REPLACE(include_file, "sites/all/", "profiles/roomify/") WHERE include_file LIKE "sites/all/%"'
drush sqlq 'UPDATE variable SET value="s:7:\"roomify\";" WHERE name = "install_profile"'
# If you don't have https://www.drupal.org/project/registry_rebuild, run:
# drush @none dl registry_rebuild-7.x
drush rr
```

**Comment by acrollet** [comment]
@nicolocaruso85 could you do a code review? Thanks!

**Review by nicolocaruso85 — APPROVED** [review]

**Pull request merged**
