### PR TITLE
Disable not translatable fields on translated edit content page.

### PR DESCRIPTION
**Pull request by nicolocaruso85**
We should disable ( and not hide!) fields that are not translatable from the translation page.
That should be done for any entity that users can manage.
screen shot 2017-03-08 at 15 36 56

### CODE REVIEW

**Review by salvoscala — COMMENTED** [review]
Looks good, I've added a helper text to disabled fields.

**Review by cecrs — CHANGES_REQUESTED** [review]
Looks mostly perfect, only thing to change are the taxonomy fields (see screenshot), we should probably change the "test" text, and the theming is a little wonky... ;)

**Comment by cecrs** [comment]
term_fields

**Comment by cecrs** [comment]
screen shot 2017-03-15 at 11 30 41 am

still seeing the 'test' text in the Location tab

**Review by cecrs — APPROVED** [review]

**Pull request merged**
