### PR TITLE
Roomify Managers should be able to edit meta tags of the homepage.

### PR DESCRIPTION
**Pull request by salvoscala**
The homepage is a special page, and meta tags are managed from this page: "admin/config/search/metatags/config/global%3Afrontpage".
Even if a Roomify Manager changes meta tags in the node, or property, set as the  homepage, these will be overridden by the ones on that page.

### CODE REVIEW

**Comment by salvoscala** [comment]
I've disabled front page meta tags so users can manage those ( even if the homepage is a Node or a Property).

Any thought?
@acrollet @cecrs

**Comment by acrollet** [comment]
@salvoscala that makes sense to me. There aren't any tags that we can only add as front page tags?

**Comment by salvoscala** [comment]
Nope, it seems all fine!

**Review by acrollet — APPROVED** [review]
CR passes

**Comment by salvoscala** [comment]
QA'd...it works fine :)

**Pull request merged**
